oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    auth-uri: https://accounts.google.com/o/oauth2/v2/auth
    redirect-uri: http://localhost:3000/oauth/google/redirect
    token-uri: https://oauth2.googleapis.com/token
    profile-uri: https://openidconnect.googleapis.com/v1/userinfo
    auth-provider-x509-cert-url: https://www.googleapis.com/oauth2/v1/certs
    grant-type: "authorization_code"
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    auth-uri: https://kauth.kakao.com/oauth/authorize
    redirect-uri: http://localhost:3000/oauth/kakao/redirect
    token-uri: https://kauth.kakao.com/oauth/token
    profile-uri: https://kapi.kakao.com/v2/user/me
    grant-type: "authorization_code"
  naver:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
    auth-uri: https://nid.naver.com/oauth2.0/authorize
    redirect-uri: http://localhost:3000/oauth/naver/redirect
    token-uri: https://nid.naver.com/oauth2.0/token
    profile-uri: https://openapi.naver.com/v1/nid/me
    grant-type: "authorization_code"